test feature

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -61,16 +61,13 @@ jobs:
                 body: output
               })
             }
-<<<<<<< Updated upstream
       - name: Dump steps context
         env:
           STEPS_CONTEXT: ${{ toJson(steps) }}
         run: echo "$STEPS_CONTEXT"
-      - name: Check on failures
-        if: steps.fail.outcome == 'failure'
-        run: exit 1
-=======
       - name: execute if branch name starts from feature
         if: ${{ contains( github.ref, 'feature/' ) }}
         run: echo "Executed"
->>>>>>> Stashed changes
+      - name: Check on failures
+        if: steps.fail.outcome == 'failure'
+        run: exit 1
